### ISSUE TITLE
Error Message in Moodle 3.1

### ISSUE THREAD

**Issue by Kathrin84** [simoncoggins/moodle-tool_capexplorer#2]
Hi Simon,

with the latest Moodle version 3.1, there's an error message occuring when opening your tool (each time):
![capexplorer_error_message](https://cloud.githubusercontent.com/assets/4711883/17581000/2f8d977a-5fa3-11e6-853f-db37a19187a2.png)

Cheers, Kathrin

**Comment by simoncoggins** [comment]
Thanks Kathrin,
I've pushed a new version (1.0.4) which should fix that issue. I've also updated it to officially support Moodle 3.1.
Simon

**Comment by Kathrin84** [comment]
Hi Simon, 
thanks for the information. Then I will update the plugin. :)
Cheers, Kathrin

**Comment by simoncoggins** [comment]
No problem.
